Repository open-mmlab/mmcv, pull requests merged in 2021-05, with the labels that each got.

#997 Support corner_pool related custom operators for onnxruntime in mmcv
  docs/onnxruntime_custom_ops.md
  docs/onnxruntime_op.md
  mmcv/ops/corner_pool.py
  mmcv/ops/csrc/onnxruntime/corner_pool.h
  mmcv/ops/csrc/onnxruntime/cpu/corner_pool.cpp
  mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp
  tests/test_ops/test_onnx.py
Labels: ONNX

#1010 Support custom operators cummax and cummin for onnxruntime
  docs/onnxruntime_custom_ops.md
  docs/onnxruntime_op.md
  mmcv/onnx/symbolic.py
  mmcv/ops/corner_pool.py
  mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp
  mmcv/ops/csrc/onnxruntime/cpu/reduce_ops.cpp
  mmcv/ops/csrc/onnxruntime/reduce_ops.h
  mmcv/ops/nms.py
  tests/test_ops/test_onnx.py
Labels: ONNX

#1018 fix basemodule
  mmcv/runner/base_module.py
Labels: Bug:P0, awaiting response

#1019 fix softnms
  mmcv/ops/nms.py
  tests/test_ops/test_nms.py
Labels: Bug:P2

#1031 [Feature] add cummax/cummin tensorrt plugin
  docs/tensorrt_custom_ops.md
  docs/tensorrt_plugin.md
  mmcv/ops/csrc/tensorrt/plugins/trt_cummaxmin.cpp
  mmcv/ops/csrc/tensorrt/plugins/trt_cummaxmin_kernel.cu
  mmcv/ops/csrc/tensorrt/plugins/trt_plugin.cpp
  mmcv/ops/csrc/tensorrt/trt_cummaxmin.hpp
  mmcv/tensorrt/tensorrt_utils.py
  tests/test_ops/test_tensorrt.py
Labels: deployment

#1034 [Feature]: add TensorRT InstanceNormalization plugin
  docs/tensorrt_custom_ops.md
  docs/tensorrt_plugin.md
  mmcv/ops/csrc/tensorrt/plugins/trt_instance_norm.cpp
  mmcv/ops/csrc/tensorrt/plugins/trt_plugin.cpp
  mmcv/ops/csrc/tensorrt/trt_instance_norm.hpp
  mmcv/ops/csrc/tensorrt/trt_serialize.hpp
  mmcv/tensorrt/tensorrt_utils.py
  tests/test_ops/test_tensorrt.py
Labels: deployment

#957 [Feature] NMS update
  docs/onnxruntime_op.md
  docs/tensorrt_plugin.md
  mmcv/ops/nms.py
  mmcv/tensorrt/__init__.py
  mmcv/tensorrt/preprocess.py
  mmcv/tensorrt/tensorrt_utils.py
  tests/test_ops/test_nms.py
  tests/test_ops/test_onnx.py
  tests/test_ops/test_tensorrt.py
  tests/test_ops/test_tensorrt_preprocess.py
Labels: ONNX
