Repository open-mmlab/mmcv, pull requests merged in 2022-12, with the labels that each got.

#2411 [Feature] Support modulated_deform_conv with cambricon MLU backend
  docs/en/understand_mmcv/ops.md
  docs/zh_cn/understand_mmcv/ops.md
  mmcv/ops/__init__.py
  mmcv/ops/modulated_deform_conv.py
  tests/test_ops/test_modulated_deform_conv.py
Labels: MLU

#2451 [Enhancement] Support LayerScale
  docs/en/api/cnn.rst
  docs/zh_cn/api/cnn.rst
  mmcv/cnn/bricks/__init__.py
  mmcv/cnn/bricks/scale.py
  mmcv/cnn/bricks/transformer.py
  tests/test_cnn/test_scale.py
  tests/test_cnn/test_transformer.py
Labels: awaiting response

#2481 add npu adapter for deformableroipool
  docs/en/understand_mmcv/ops.md
  docs/zh_cn/understand_mmcv/ops.md
  mmcv/ops/csrc/pytorch/npu/deform_roi_pool.cpp
  tests/test_ops/test_deform_roi_pool.py
Labels: NPU
