Repository open-mmlab/mmcv, pull requests merged in 2022-04, with the labels that each got.

#1847 [Fix] GELU got an unexpected keyword argument 'inplace'
  mmcv/cnn/bricks/conv_module.py
Labels: Bug

#1828 [Fix] Fix Python3.10 CI
  .github/workflows/build.yml
  requirements/test.txt
Labels: size/XS

#1789 [Enhancement] Fix collect_env on Windows
  mmcv/utils/env.py
  tests/test_utils/test_env.py
Labels: Windows, size/XS

#1846 [Feature] Support finding free port in _init_dist_slurm()
  mmcv/runner/dist_utils.py
Labels: size/XS

#1814 [Enhancment] Optimize correlation
  mmcv/ops/csrc/common/cuda/correlation_cuda.cuh
  mmcv/ops/csrc/pytorch/cuda/correlation_cuda.cu
Labels: size/XS

#1844 [Enhancement] Speed up Registry initialization
  mmcv/utils/registry.py
Labels: size/XS

#1770 [Feature] Support PyTorch backend on MLU
  .github/workflows/build.yml
  mmcv/__init__.py
  mmcv/device/__init__.py
  mmcv/device/mlu/__init__.py
  mmcv/device/mlu/_functions.py
  mmcv/device/mlu/data_parallel.py
  mmcv/device/mlu/distributed.py
  mmcv/device/mlu/scatter_gather.py
  mmcv/device/mlu/utils.py
  mmcv/ops/csrc/common/pytorch_cpp_helper.hpp
  mmcv/ops/csrc/common/pytorch_mlu_helper.hpp
  mmcv/runner/dist_utils.py
  setup.py
  tests/test_device/test_mlu/test_mlu_parallel.py
Labels: MLU

#1824 NMS with CUDA only
  mmcv/ops/csrc/common/cuda/nms_cuda_kernel.cuh
  mmcv/ops/csrc/pytorch/cuda/nms_cuda.cu
Labels: Op, size/XS

#1792 Make sure padding size is not negative
  mmcv/image/geometric.py
  tests/test_image/test_geometric.py
Labels: Enhancement, size/XS

#1834 [Enhancement] Support None in DictAction
  mmcv/utils/config.py
  tests/test_utils/test_config.py
Labels: Enhancement, size/XS

#1867 [Enhance] Enhance get_torchvision_models
  mmcv/model_zoo/torchvision_0.12.json
  mmcv/runner/checkpoint.py
  tests/test_load_model_zoo.py
Labels: Enhancement

#1718 [Enhancement] Optimize bbox overlap
  mmcv/ops/bbox.py
  mmcv/ops/csrc/common/cuda/bbox_overlaps_cuda_kernel.cuh
  mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.cu
  tests/test_ops/test_bbox.py
Labels: Enhancement, Op

#1878 [Feature] Add rotated_feature_align cpu & onnxruntime implementation
  mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp
  mmcv/ops/csrc/onnxruntime/cpu/rotated_feature_align.cpp
  mmcv/ops/csrc/onnxruntime/rotated_feature_align.h
  mmcv/ops/csrc/pytorch/cpu/rotated_feature_align.cpp
  mmcv/ops/rotated_feature_align.py
  tests/test_ops/test_onnx.py
  tests/test_ops/test_rotated_feature_align.py
Labels: ONNX, Op
