Repository open-mmlab/mmcv, pull requests merged in 2022-03, with the labels that each got.

#1795 [Docs] Fix a wrong example in `DefaultOptimizerConstructor`
  mmcv/runner/optimizer/default_constructor.py
Labels: size/XS

#1797 [Docs] Fix minor typo in docs/en/config.md
  docs/en/understand_mmcv/config.md
  docs/en/understand_mmcv/registry.md
Labels: size/XS

#1799 Fixed typo in docs/en/understand_mmcv/cnn.md
  docs/en/understand_mmcv/cnn.md
Labels: size/XS

#1798 [Docs] minor typo fix in docs/en/understand_mmcv/data_process.md
  docs/en/understand_mmcv/data_process.md
Labels: size/XS

#1788 [Feature] Add worker_init_fn
  mmcv/utils/__init__.py
  mmcv/utils/seed.py
Labels: size/XS

#1800 [Enhancement] Add PyTorch1.11.0 CI
  .github/workflows/build.yml
  tests/test_parallel.py
Labels: size/XS

#1796 [Feature] Support shallow copy for Config
  mmcv/utils/config.py
  tests/test_utils/test_config.py
Labels: size/XS

#1806 bump version to v1.4.7
  mmcv/version.py
Labels: size/XS

#1807 [Fix] Add @cacheable_method in transform wrapper `RandomChoice`
  mmcv/transforms/utils.py
  mmcv/transforms/wrappers.py
  tests/test_transforms/test_transforms_wrapper.py
Labels: size/XS

#1811 [Fix] Update unittest for mmdet3d ops
  tests/test_ops/test_gather_points.py
  tests/test_ops/test_roiaware_pool3d.py
  tests/test_ops/test_roipoint_pool3d.py
  tests/test_ops/test_scatter_points.py
Labels: size/XS

#1704 [Fix] Fix rocm support
  setup.py
  tests/test_ops/test_onnx.py
Labels: WIP, ROCm

#1804 [Fix] Set keypoints not in the cropped image invisible
  mmcv/transforms/processing.py
  tests/test_transforms/test_transforms_processing.py
Labels: size/XS

#1815 [Enhancement] Add Python3.10 CI
  .github/workflows/build.yml
Labels: size/XS

#1802 [fix] config ignore imported modules and functions
  mmcv/utils/config.py
  tests/data/config/l.py
  tests/data/config/n.py
Labels: size/XS

#1801 [Fix] Fix MultiScaleFlipAug
  mmcv/transforms/processing.py
  tests/test_transforms/test_transforms_processing.py
Labels: size/XS

#1823 Fix ms deform attn
  mmcv/ops/csrc/common/cuda/ms_deform_attn_cuda_kernel.cuh
  mmcv/ops/csrc/pytorch/cuda/ms_deform_attn_cuda.cu
Labels: size/XS

#1822 [Bug] Fix voxelization bug
  mmcv/ops/csrc/common/cuda/voxelization_cuda_kernel.cuh
Labels: size/XS

#1816 [Fix] Fix PyTorch1.11 Dist Remove _sync_params
  mmcv/parallel/distributed.py
Labels: size/XS

#1826 [Feature]: Reformat resize config
  mmcv/transforms/processing.py
  tests/test_transforms/test_transforms_processing.py
Labels: size/XXL

#1838 Fixed a typo in multi_scale_deform_attn.py
  mmcv/ops/multi_scale_deform_attn.py
Labels: size/XS

#1696 [Feature] Support tin_shift with cambricon MLU backend
  mmcv/ops/csrc/common/mlu/tin_shift_mlu_kernel.mlu
  mmcv/ops/csrc/pytorch/mlu/tin_shift_mlu.cpp
  mmcv/ops/csrc/pytorch/tin_shift.cpp
  mmcv/ops/tin_shift.py
  tests/test_ops/test_tin_shift.py
Labels: MLU

#1831 [Fix] fix some typo in transforms
  mmcv/transforms/loading.py
  mmcv/transforms/processing.py
  tests/test_transforms/test_transforms_loading.py
Labels: size/XS

#1784 [Fix] Fix typos, init funcs, cacheable method of part3 of data transforms
  mmcv/transforms/__init__.py
  mmcv/transforms/processing.py
  tests/test_transforms/test_transforms_processing.py
Labels: size/XS

#1627 [Feature] Support for linearly learning rate decay
  docs/en/community/contributing.md
  mmcv/runner/__init__.py
  mmcv/runner/hooks/__init__.py
  mmcv/runner/hooks/lr_updater.py
  mmcv/runner/hooks/momentum_updater.py
  tests/test_runner/test_hooks.py
Labels: Feature
